### ISSUE TITLE
Any way to allow a plugin control over it's writer priority?

### ISSUE THREAD

**Issue by tlambert03** [napari/npe2#129] opened 2022-03-14 01:19 UTC
In converting over to using only npe2 interface in napari, I came across an issue where it was very difficult to get `get_writer` to pick the lossless writer by default when writing an image with `write_layer_data_with_plugins`:

```python
        # build in a temporary directory and then move afterwards,
        # it makes cleanup easier if an exception is raised inside.
        with TemporaryDirectory(dir=path) as tmp:
            # Loop through data for each layer
            for layer_data_tuple in layer_data:
                _, meta, _ = layer_data_tuple
                # Get hook caller according to layer type

                # Create full path using name of layer
                full_path = abspath_or_url(os.path.join(tmp, meta['name']))
                # Write out data using first plugin found or named plugin if provided
                written.extend(
                    io_utils.write(
                        path=full_path,
                        layer_data=[layer_data_tuple],
                        plugin_name=plugin_name,
                    )
                )
            for fname in os.listdir(tmp):
                shutil.move(os.path.join(tmp, fname), path)
```

The tiff writer does appear first in the list of single image writers, but there's a few things in iter_compatible writers that mangle the order.  Ultimately, I needed to remove these two lines from `_writer_key` in order to get it to choose the earlier listed `tiff` writer instead of the lossy writer:

```
            # 3. then sort by the number of listed extensions
            #    (empty set of extensions goes last)
            ext_len = len(writer.filename_extensions)

            # 4. finally group related extensions together
            exts = writer.filename_extensions
```

But, obviously, that's just a hack.  @nclack, we didn't particularly anticipate this internal usage, but do you have any thoughts on how we might update our `write_layer_data_with_plugins` to maintain the current behavior while using npe2?

**Comment by tlambert03** [comment] 2022-03-14 01:22
put another way, how might we be able to prioritize tiff write when not providing an extension specifically:
```
In [11]: pm.get_writer('no_ext_image', ['image'])
Out[11]:
(
    WriterContribution(command='napari.write_image', layer_types=['image'], filename_extensions=['.jpg', '.jpeg', '.j2c', '.j2k', '.jfif', '.jp2', '.jpc', '.jpe', '.jpf', '.jpx', '.mpo'], display_name='lossy'),
    'no_ext_image.jpg'
)

```

**Comment by nclack** [comment] 2022-04-01 21:34
We discussed this in the plugin working meeting (a while ago now 😬 ). I believe the idea was to prioritize writers according to the order that they are listed in the manifest. Is this already happening implicitly?

If so, docs/tests to that effect should be added before closing this.

**Comment by tlambert03** [comment] 2022-04-01 21:37
> I believe the idea was to prioritize writers according to the order that they are listed in the manifest. Is this already happening implicitly?

no, it's not happening because of the lines mentioned above in the original post:

https://github.com/napari/npe2/blob/83d161aafcf7d9cd7607bf82c164a62e6450ddbb/npe2/_plugin_manager.py#L166-L184

**Comment by nclack** [comment] 2022-04-01 22:07
Reading is fundamental. Thanks for the correction.

The sorting was designed to control how they are listed in the "Save As" dialog in napari. I liked, for example, that different plugins supporting '.tif' might be listed next to one another. That logic probably belongs more on the napari side since the requirement comes from the view.

**Comment by tlambert03** [comment] 2022-06-10 19:25
running into this again.  Is this on your radar @nclack?  Or should I do this?

**Comment by nclack** [comment] 2022-06-11 02:17
Thanks 🙏 go for it!

**Closed** 2022-06-12 12:58 UTC
